### ISSUE TITLE
Cannot read property 'clearCanvas' of undefined

### ISSUE THREAD

**Issue by vankasteelj** [jaruba/pw-wcjs-player#1]
line 801: `this.renderer.clearCanvas();`

`this.renderer` is undefined, using url (http://127.0.0.1:port) pointing to a peerflix-streamed mkv file

**Comment by jaruba** [comment]
https://github.com/jaruba/pw-wcjs-player/blob/master/package.json#L21
https://github.com/jaruba/wcjs-renderer/blob/master/index.js#L203

should work.. don't see how it couldn't.. as I'm using my fork of `wcjs-renderer`.

**Comment by vankasteelj** [comment]
![2015-11-20_03-23-36](https://cloud.githubusercontent.com/assets/12599850/11290321/1e45039c-8f36-11e5-91c0-d3796bf912a2.png)

Powder from github, up to date
